sudden-death-time: 3600 # seconds
warning-times: [60, 30, 15, 10, 5, 4, 3, 2, 1] # seconds
grace-period: 30 # seconds
respawn-invincibility: 10 # seconds
indestructable-spawners: true
prevent-bed-explosions: true
prevent-respawn-anchor-explosions: true
must-kill-dragon-to-win: true
teams:
  redstone: "RED"
  lapis: "BLUE"
  emerald: "GREEN"
  gold: "YELLOW"
  diamond: "AQUA"
  quartz: "WHITE"
  purpur: "LIGHT_PURPLE"
  iron: "GRAY"
  crimson: "DARK_RED"
  ice: "DARK_BLUE"
  slime: "DARK_GREEN"
  glowstone: "GOLD"
  prismarine: "DARK_AQUA"
  netherite: "DARK_GRAY"
  chorus: "DARK_PURPLE"
  obsidian: "BLACK"