sudden-death-time: 30 # minutes
countdown-time: 3 # seconds
grace-period: 30 # seconds
respawn-invincibility: 15 # seconds
portal-invincibility: 5 # seconds
warning-times: [60, 30, 15, 10, 5, 4, 3, 2, 1] # seconds
portal-alerts: true
world-border: true
prevent-bed-explosions: true
prevent-respawn-anchor-explosions: true
indestructable-spawners: true
must-kill-dragon-to-win: true
lower-dragon-health-in-sudden-death: true
hide-spectator-advancements: true
give-compass: true
keep-armor: true
keep-tools: true
give-armor: false
efficient-tools: false
smelt-ores: false
cook-food: false
randomize-drops: false
permanent-potions: false
teams:
  redstone: "RED"
  lapis: "BLUE"
  emerald: "GREEN"
  gold: "YELLOW"
  diamond: "AQUA"
  quartz: "WHITE"
  purpur: "LIGHT_PURPLE"
  iron: "GRAY"
  crimson: "DARK_RED"
  ice: "DARK_BLUE"
  slime: "DARK_GREEN"
  glowstone: "GOLD"
  prismarine: "DARK_AQUA"
  netherite: "DARK_GRAY"
  chorus: "DARK_PURPLE"
  obsidian: "BLACK"
