name: SpeedrunShowdown
version: 2.0
author: KaiNakamura
main: com.github.speedrunshowdown.SpeedrunShowdown
api-version: 1.19.3
load: STARTUP
commands:
  start:
    description: Start the game
    permission: speedrunshowdown
    usage: /start
  stop:
    description: Stop the game
    permission: speedrunshowdown
    usage: /stop
  config:
    description: Open config gui
    permission: speedrunshowdown
    usage: /config
  resume:
    description: Resume the game (to be used if the server crashes during a game)
    permission: speedrunshowdown
    usage: /resume [minutes] [seconds]
  suddendeath:
    description: Set time until sudden death
    permission: speedrunshowdown
    usage: /suddendeath [minutes] [seconds]
  givecompass:
    description: Give a tracking compass
    permission: speedrunshowdown
    usage: /givecompass [player]
  givearmor:
    description: Give armor
    permission: speedrunshowdown
    usage: /givearmor [player]
  win:
    description: Declare the winning team
    permission: speedrunshowdown
    usage: /win (team|player)
  removebossbars:
    description: Removes all boss bars (to be used if something glitches out)
    permission: speedrunshowdown
    usage: /removebossbars
permissions:
  speedrunshowdown:
    description: Allows speedrunshowdown commands
    default: op